// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4NjgWl9qa9wkb1EN-nB9wgWmzK815No',
    appId: '1:388133875376:web:ad058507ea0b0f86cd5575',
    messagingSenderId: '388133875376',
    projectId: 'nexosaude',
    authDomain: 'nexosaude.firebaseapp.com',
    storageBucket: 'nexosaude.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnbABukD4-bLZyFeW8zDsiRmoGwc6UtMw',
    appId: '1:388133875376:android:13c45cf81561b5b8cd5575',
    messagingSenderId: '388133875376',
    projectId: 'nexosaude',
    storageBucket: 'nexosaude.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqrmbr6zJ7Q77d9huDIxk_jXr8Q1xHCUE',
    appId: '1:388133875376:ios:c79f4a758e19e717cd5575',
    messagingSenderId: '388133875376',
    projectId: 'nexosaude',
    storageBucket: 'nexosaude.firebasestorage.app',
    iosBundleId: 'com.example.odontoControle',
  );
}
