// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRYUvuPM3-CHwGNmVJd5Ikk46PRCvdmZ8',
    appId: '1:698345542344:web:48ffb4bc8865af973d8bfd',
    messagingSenderId: '698345542344',
    projectId: 'odontocontrole-1c701',
    authDomain: 'odontocontrole-1c701.firebaseapp.com',
    storageBucket: 'odontocontrole-1c701.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLqpd_cMBXSRqOIIHnlap_m0tESv-q6Y',
    appId: '1:698345542344:android:26c162f16d8768a93d8bfd',
    messagingSenderId: '698345542344',
    projectId: 'odontocontrole-1c701',
    storageBucket: 'odontocontrole-1c701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1bsNtT8o5-UQ05cnNHOrCNO1o_KxV_Ig',
    appId: '1:698345542344:ios:77c6a6228e2eac3e3d8bfd',
    messagingSenderId: '698345542344',
    projectId: 'odontocontrole-1c701',
    storageBucket: 'odontocontrole-1c701.firebasestorage.app',
    iosBundleId: 'com.example.odontoControle',
  );
}
